### ISSUE TITLE
rejestracja, logowanie i kontakt - napisy po polsku

### ISSUE THREAD

**Issue by szelma007** [baskap/bestlawyers#28]
Na górnym pasku znajdują się odnośniki do logowania i rejestracji. 
Jak wybierze się rejestrację to po najechaniu kursorem (i chwilę poczekaniu) na pole do wpisania np. imienia pojawia się napis "Proszę wypełnić to pole". 

Na zakładce kontakt po najechaniu na pole np. imię pojawia się taki sam komunikat.

**Comment by szelma007** [comment]
Napisy takiego nie ma tylko w IE-9

**Comment by baskap** [comment]
To zostawiamy - zależy od ustawień przeglądarki i niech juz taks obie będdzie
