### ISSUE TITLE
zawijanie tekstu - pasek prośby o konsulację

### ISSUE THREAD

**Issue by szelma007** [baskap/bestlawyers#34]
w IE - 10 przy częściowym zmniejszeniu okna na dolnym niebieskim pasku (z prośbą o konsultację) nie rozdziela tekstu "If you have any legal problem ... We are available  -  request free consultation" tylko pozostaje poza obszarem okna.

**Comment by baskap** [comment]
Mi rozdziela ...

**Comment by baskap** [comment]
Już powinno być ok
