### ISSUE TITLE
telefon - blog - pasek boczny

### ISSUE THREAD

**Issue by szelma007** [baskap/bestlawyers#37]
Nie ma znaczenia czy wybieramy Left czy Right Sidebar (oraz Blog Item . ..) z menu Blog (wyświetlane jest to samo)

**Comment by baskap** [comment]
Chyba tak ma być - na komórkach czasami się ukrywa pewne informacje i zostawia najważniejsze. Uznałam, ze lista practice area nie jest potrzebna w wydaniu komórkowym
