### ISSUE TITLE
dokumentacja - telefon (wystający link)

### ISSUE THREAD

**Issue by szelma007** [baskap/bestlawyers#44]
Na telefonie (w wersji pionowej) w menu (Theme configuration - GoogleMap configuration) na dole tego podmenu (przed Contact form configuratinon) jest link https://developers.google.com/maps/documentation/javascript/get-api-key, który podzielił się na - (kresce) i wystaje poza szerokość pozostałego tekstu.
Nie wiem jak przy ewentualnym zmniejszeniu zachowa sie ramka w podmenu "jQuery plugins", oraz czarny dolny pasek z napisem "Ready Olsztyn ..." teraz jest zwężony do szerokości podstawowego tekstu (nie jest na całej szerokości).

**Comment by bposzewiecka** [comment]
Kurcze tego nikt nie będzie oglądał na komórkach, wiec mysle ze mozna zostawic tak jak jest
