### ISSUE TITLE
windows phone - home komunikat

### ISSUE THREAD

**Issue by szelma007** [baskap/bestlawyers#46]
Jeśli w IE przełączę na Windows Phone to będąc na zakładce "Home" przesunę kilka razy stronę góra - dół- góra ... , pojawia się komunikat  

[windows phone komunikat_home.docx](https://github.com/baskap/bestlawyers/files/726254/windows.phone.komunikat_home.docx)

**Comment by baskap** [comment]
Jak ty to znajdujesz? Masakra

**Comment by baskap** [comment]
Już powinno być ok
